### ISSUE TITLE
zone classic editions

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/peq-expansions#155]
- [ ] freportw replaced with freeportwest during PoR (11)
- [ ] nektulos replaced with eqg edition during PoR 11
- [ ] ecommons replaced with commonlands during PoR 11
- [ ] cazicthule revamped #116 
- [ ] freporte replaced during PoR (11) with freeporteast
- [ ] commons replaced with commonlands during PoR 11 
- [ ] freportn replaced with freeportwest during PoR (11)
- [ ] nro replaced during por (11) to northro
- [ ] paw revamped during LDON #141 
- [ ] pohate replaced during velious (2) to pohateb #115 
- [ ] lavastorm kept same name, but has s3d/eqg during DoN (9)
- [ ] sro changed to southro during PoR (11)
- [ ] runnyeye not changed, but classic edition spawns needed #145 
- [ ] oasis replaced with southro during por (11)
- [ ] highkeep was NOT replaced with highkeeppass during TSS (12).. i don't see highkeeppass ever being used, even on latest live?
- [ ] highpass replaced during TSS (12) with highpasshold more info #56 
- [ ] misty changed to mistythicket during TBS (13)
- [ ] tox replaced with toxxulia TBS (13)
- [ ] innothule replaced with innothuleb during TBS (13)
- [ ] steamfont replaced with steamfontmtns during SoF (14)
- [ ] oot replaced with oceanoftears during TBS (13)
- [ ] arena replaced with arena2 during possibly PoR? 11
