### ISSUE TITLE
rivervale

### ISSUE THREAD

**Issue by xackery** [ProjectEQ/peq-expansions#21]
- [x] Wendel_Deeppockets - 5
- [x] Dalorio_Blistbobble - 4 (newbie armor quests)
- [x] Exterminator_Sutten - 5
- [x] Fento_Jalla - 7
- [x] a_rodent - 5
- [x] Teelie_Meegles - 5
- [x] Soulbinder_Hoggle_Grubbytoe - 3
- [x] Megosh_Thistlethorn - 4 (newbie armor quests)
- [x] Shayde_Higginsbot - 10 - 13th anniversary noted in #24
- [x] Shutter_Silentstep - 1
- [x] a_halfling_acolyte - 2
- [x] Jimbledorp_Heptybak - 6
- [x] Rellix - 9
- [x] Artisan_Bill_Whistletop - 9
- [x] Laryen_Lycanthrope - noted in #23
- [x] a_Frostfell_Goblin - 11 - noted in #22 
- [x] Hargar_the_Velium_Chef - 11 - noted in #22 
- [x] Fireworks_Engineer_Fabdabus - 11 - noted in #22 
- [x] Santug_Claugg - 11 - frostfell noted in #22
